// Supabase configuration
const SUPABASE_URL = window.ENV?.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = window.ENV?.SUPABASE_ANON_KEY || '';

// Check if keys are configured
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('Missing API keys. Please configure environment variables.');
}

// Playlist structure
const PLAYLISTS = [
    {
        id: 'beginner-0-3',
        title: 'Beginner Weeks 0-3',
        description: 'Workout playlist for Week 0 to 3',
        videos: [
            {
                id: 'ABMlz_M3gFc',
                title: 'Squat',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment:["Chair (For Support)", "No Chair", "Weight (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/ABMlz_M3gFc/hqdefault.jpg',
            },{
                id: 'LRALTxfWzpA',
                title: 'Hip Hinge',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Dowel (For Support)", "Weights (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/LRALTxfWzpA/hqdefault.jpg',
            },{
                id: 'ZKec-ggfkmE',
                title: 'Reverse Lunge',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (For Support)", "No Chair"],
                thumbnail: 'https://img.youtube.com/vi/ZKec-ggfkmE/hqdefault.jpg',
            },{
                id: 'it4y0lVzvFg',
                title: 'Single Leg Deadlift',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (For Support)", "No Chair"],
                thumbnail: 'https://img.youtube.com/vi/it4y0lVzvFg/hqdefault.jpg',
            },{
                id: 'JPext-e_lws',
                title: 'Cloth Slide',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Cloth, Chair & Table"],
                thumbnail: 'https://img.youtube.com/vi/JPext-e_lws/hqdefault.jpg',
            },{
                id: 'YjH7iVbzNLA',
                title: 'Shoulder Active Motion - Forward',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: ["None", "Weights (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/YjH7iVbzNLA/hqdefault.jpg',
            },{
                id: 'bl36zCco4nM',
                title: 'Shoulder Active Motion - Lateral',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Dowel or Broomstick"],
                thumbnail: 'https://img.youtube.com/vi/bl36zCco4nM/hqdefault.jpg',
            },{
                id: 'hQbv0Z9QPkw',
                title: 'Isometric Shoulder Contraction - External Rotation',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Table & Chair"],
                thumbnail: 'https://img.youtube.com/vi/hQbv0Z9QPkw/hqdefault.jpg',
            },{
                id: 'RCHWmmnE2xM',
                title: 'Isometric Shoulder Contraction - Front Raise',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Table & Chair"],
                thumbnail: 'https://img.youtube.com/vi/RCHWmmnE2xM/hqdefault.jpg',
            },{
                id: 'qgNeGxt2CE0',
                title: 'Hands Up Wall',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Wall"],
                thumbnail: 'https://img.youtube.com/vi/qgNeGxt2CE0/hqdefault.jpg',
            },{
                id: '_vlYsmleqgg',
                title: 'Hand Squeeze',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Cloth or Ball or Towel"],
                thumbnail: 'https://img.youtube.com/vi/_vlYsmleqgg/hqdefault.jpg',
            },{
                id: 'GegYjbIXcMo',
                title: 'Reach Behind Back',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/GegYjbIXcMo/hqdefault.jpg',
            },{
                id: 'HEYLsGviHiI',
                title: 'Tandem Stand',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 45,
                equipment: ["Chair (For Support)", "No Chair"],
                thumbnail: 'https://img.youtube.com/vi/HEYLsGviHiI/hqdefault.jpg',
            },{
                id: 'sY5n7wpVLXI',
                title: 'Single Leg Stand',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 45,
                equipment: ["A Chair or Wall"],
                thumbnail: 'https://img.youtube.com/vi/sY5n7wpVLXI/hqdefault.jpg',
            }
        ]
    },
    {
        id: 'advanced-4-6',
        title: 'Advanced Weeks 4-6',
        description: 'Workout playlist for Week 4 to 6',
        videos: [
            {
                id: 'ABMlz_M3gFc',
                title: 'Squat',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Chair (For Support)", "No Chair", "Weight (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/ABMlz_M3gFc/hqdefault.jpg',
            },{
                id: 'LRALTxfWzpA',
                title: 'Hip Hinge',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Dowel (For Support)", "Weights (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/LRALTxfWzpA/hqdefault.jpg',
            },{
                id: 'ZKec-ggfkmE',
                title: 'Reverse Lunge',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (For Support)", "No Chair"],
                thumbnail: 'https://img.youtube.com/vi/ZKec-ggfkmE/hqdefault.jpg',
            },{
                id: 'it4y0lVzvFg',
                title: 'Single Leg Deadlift',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (For Support)", "No Chair"],
                thumbnail: 'https://img.youtube.com/vi/it4y0lVzvFg/hqdefault.jpg',
            },{
                id: 'WP5eJJmTk6o',
                title: 'Incline Push Up',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Wall or Table"],
                thumbnail: 'https://img.youtube.com/vi/WP5eJJmTk6o/hqdefault.jpg',
            },{
                id: 'N6b1q1Lcjco',
                title: 'Single Arm Support Rows',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Chair & Weight"],
                thumbnail: 'https://img.youtube.com/vi/N6b1q1Lcjco/hqdefault.jpg',
            },{
                id: 'wUY_uBTHDUM',
                title: 'Upright Rows',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Weights"],
                thumbnail: 'https://img.youtube.com/vi/wUY_uBTHDUM/hqdefault.jpg',
            },{
                id: 'df6Ylaa4zfE',
                title: 'Band Pull Apart',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Resistance Band"],
                thumbnail: 'https://img.youtube.com/vi/df6Ylaa4zfE/hqdefault.jpg',
            },{
                id: 'TlW7jhOUPNI',
                title: 'Heel to Toe Walk',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/TlW7jhOUPNI/hqdefault.jpg',
            },{
                id: 'mehvCsI5WJw',
                title: 'Band External Rotation',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Resistance Band"],
                thumbnail: 'https://img.youtube.com/vi/mehvCsI5WJw/hqdefault.jpg',
            },{
                id: '_IeZdX1-tLQ',
                title: 'Walk on Toes',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/_IeZdX1-tLQ/hqdefault.jpg',
            }
        ]
    }
];

// Initialize Supabase
window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
