// Supabase configuration
const SUPABASE_URL = window.ENV?.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = window.ENV?.SUPABASE_ANON_KEY || '';

// Check if keys are configured
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error('Missing API keys. Please configure environment variables.');
}

// Playlist structure
const PLAYLISTS = [
    {
        id: 'beginner-0-3',
        title: 'Beginner Weeks 0-3',
        description: 'Workout playlist for Week 0 to 3',
        videos: [
            {
                id: 'bl36zCco4nM',
                title: 'Shoulder Active Motion - Lateral',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Dowel or Broomstick"],
                thumbnail: 'https://img.youtube.com/vi/bl36zCco4nM/hqdefault.jpg',
            },{
                id: 'RCHWmmnE2xM',
                title: 'Isometric Shoulder Contraction - Front Raise',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Table & Chair"],
                thumbnail: 'https://img.youtube.com/vi/RCHWmmnE2xM/hqdefault.jpg',
            },{
                id: 'tH8scH-a4RE',
                title: 'Reach Behind Back',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/tH8scH-a4RE/hqdefault.jpg',
            },{
                id: 'Curl_DUPfuY',
                title: 'Reverse Lunge',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/Curl_DUPfuY/hqdefault.jpg',
            },{
                id: 'I2UvsqRVSus',
                title: 'Single Leg Deadlift',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/I2UvsqRVSus/hqdefault.jpg',
            },{
                id: 'XU1og9bz_Lw',
                title: 'Single Leg Stand',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 45,
                equipment: ["A Chair or Wall"],
                thumbnail: 'https://img.youtube.com/vi/XU1og9bz_Lw/hqdefault.jpg',
            },{
                id: 'CNhgzve4B5s',
                title: 'Squat',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment:["Chair (Easier)", "No Chair (More Challenging)", "Weight (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/CNhgzve4B5s/hqdefault.jpg',
            },{
                id: 'BLjrwrql5ps',
                title: 'Tandem Stand',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 45,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/BLjrwrql5ps/hqdefault.jpg',
            },{
                id: 'JPext-e_lws',
                title: 'Cloth Slide',
                sets: 3,
                reps: 0,
                needsEachSide: true,
                seconds: 30,
                equipment: ["A Cloth, Chair & Table"],
                thumbnail: 'https://img.youtube.com/vi/JPext-e_lws/hqdefault.jpg',
            },{
                id: '_vlYsmleqgg',
                title: 'Hand Squeeze',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Cloth or Ball or Towel"],
                thumbnail: 'https://img.youtube.com/vi/_vlYsmleqgg/hqdefault.jpg',
            },{
                id: 'qgNeGxt2CE0',
                title: 'Hands Up Wall',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Wall"],
                thumbnail: 'https://img.youtube.com/vi/qgNeGxt2CE0/hqdefault.jpg',
            },{
                id: 'Yd5y1qkxNyg',
                title: 'Hip Hinge',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Dowel (Easier)", "Weights (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/Yd5y1qkxNyg/hqdefault.jpg',
            },{
                id: '1L2dCDzBzGk',
                title: 'Isometric Shoulder Contraction - External Rotation',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: ["A Table & Chair"],
                thumbnail: 'https://img.youtube.com/vi/1L2dCDzBzGk/hqdefault.jpg',
            },{
                id: '1lU9gsrWdic',
                title: 'Shoulder Active Motion - Forward',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: ["None (Easier)", "Weights (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/1lU9gsrWdic/hqdefault.jpg',
            }
        ]
    },
    {
        id: 'advanced-4-6',
        title: 'Advanced Weeks 4-6',
        description: 'Workout playlist for Week 4 to 6',
        videos: [
            {
                id: 'Curl_DUPfuY',
                title: 'Reverse Lunge',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/Curl_DUPfuY/hqdefault.jpg',
            },{
                id: 'N6b1q1Lcjco',
                title: 'Single Arm Support Rows',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["A Chair & Weight"],
                thumbnail: 'https://img.youtube.com/vi/N6b1q1Lcjco/hqdefault.jpg',
            },{
                id: 'I2UvsqRVSus',
                title: 'Single Leg Deadlift',
                sets: 3,
                reps: 8,
                needsEachSide: true,
                seconds: 0,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/I2UvsqRVSus/hqdefault.jpg',
            },{
                id: 'CNhgzve4B5s',
                title: 'Squat',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Chair (Easier)", "No Chair (More Challenging)", "Weight (Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/CNhgzve4B5s/hqdefault.jpg',
            },{
                id: 'WN81Wbx7lwY',
                title: 'Upright Rows',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Weights"],
                thumbnail: 'https://img.youtube.com/vi/WN81Wbx7lwY/hqdefault.jpg',
            },{
                id: '_IeZdX1-tLQ',
                title: 'Walk on Toes',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/_IeZdX1-tLQ/hqdefault.jpg',
            },{
                id: 'mehvCsI5WJw',
                title: 'Band External Rotation',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Resistance Band"],
                thumbnail: 'https://img.youtube.com/vi/mehvCsI5WJw/hqdefault.jpg',
            },{
                id: 'df6Ylaa4zfE',
                title: 'Band Pull Apart',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Resistance Band"],
                thumbnail: 'https://img.youtube.com/vi/df6Ylaa4zfE/hqdefault.jpg',
            },{
                id: 'TlW7jhOUPNI',
                title: 'Heel to Toe Walk',
                sets: 3,
                reps: 0,
                needsEachSide: false,
                seconds: 30,
                equipment: [],
                thumbnail: 'https://img.youtube.com/vi/TlW7jhOUPNI/hqdefault.jpg',
            },{
                id: 'Yd5y1qkxNyg',
                title: 'Hip Hinge',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["Dowel (Easier)", "Weights (More Challenging)"],
                thumbnail: 'https://img.youtube.com/vi/Yd5y1qkxNyg/hqdefault.jpg',
            },{
                id: 'WP5eJJmTk6o',
                title: 'Incline Push Up',
                sets: 3,
                reps: 8,
                needsEachSide: false,
                seconds: 0,
                equipment: ["A Wall or Table"],
                thumbnail: 'https://img.youtube.com/vi/WP5eJJmTk6o/hqdefault.jpg',
            }
        ]
    }
];

// Initialize Supabase
window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
